# Generated by Django 3.2.8 on 2022-03-24 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('help', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='image',
            field=models.TextField(blank=True, verbose_name='Скриншот'),
        ),
    ]
