# Generated by Django 3.2.8 on 2022-03-24 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('help', '0002_alter_feedback_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='date',
            field=models.CharField(max_length=100, verbose_name='Время'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='device',
            field=models.CharField(max_length=100, verbose_name='Устройства'),
        ),
    ]
