# Generated by Django 3.2.8 on 2022-06-05 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=170, verbose_name='Тақырып')),
                ('body', models.TextField(verbose_name='Мәтін')),
                ('image', models.ImageField(blank=True, upload_to='image')),
                ('date', models.CharField(blank=True, max_length=170, verbose_name='Уақыты')),
            ],
        ),
    ]
