# Generated by Django 3.2.8 on 2022-06-05 04:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя категори')),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passname', models.CharField(max_length=255, verbose_name='Тип орнамента')),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TypeOfOrnament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Тип орнамента')),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(verbose_name='Комментарий к заказу')),
                ('price', models.DecimalField(decimal_places=0, max_digits=9, verbose_name='Цена')),
                ('des_image', models.TextField(blank=True, verbose_name='Фото (Base64)')),
                ('client_first_name', models.CharField(default='Anonymous_user', max_length=50, verbose_name='Имя')),
                ('client_last_name', models.CharField(default='Anonymous_user', max_length=50, verbose_name='Фамилия')),
                ('whatsapp', models.CharField(default='Anonymous_user', max_length=15, verbose_name='Whatsapp')),
                ('phone_number', models.CharField(default='Anonymous_user', max_length=15, verbose_name='Телефон')),
                ('ip', models.CharField(blank=True, max_length=50, verbose_name='Ip')),
                ('date', models.CharField(blank=True, max_length=50, verbose_name='Время')),
                ('system_info', models.CharField(default='Anonymous_user', max_length=150, verbose_name='Системный информация')),
                ('ornament_info', models.CharField(default='Anonymous_user', max_length=90, verbose_name='Использованные узоры')),
                ('number', models.DecimalField(decimal_places=0, default=1, max_digits=9, verbose_name='Количесвто')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maker.category', verbose_name='Категрия')),
            ],
        ),
        migrations.CreateModel(
            name='OrnamentFragment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_base64', models.TextField(verbose_name='Изоброжение (Base64)')),
                ('price', models.DecimalField(decimal_places=2, default=5000, max_digits=9, verbose_name='Цена орнамента')),
                ('types', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maker.typeofornament', verbose_name='Тип орнамента')),
            ],
        ),
    ]
