# Generated by Django 3.2.8 on 2022-01-05 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maker', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='date',
        ),
        migrations.RemoveField(
            model_name='product',
            name='ipaddress',
        ),
    ]
