# Generated by Django 3.2.8 on 2022-06-05 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='latitude',
            field=models.CharField(blank=True, max_length=30, verbose_name='Широта'),
        ),
        migrations.AddField(
            model_name='product',
            name='longitude',
            field=models.CharField(blank=True, max_length=30, verbose_name='Долгота'),
        ),
    ]
