# Generated by Django 3.2.8 on 2022-01-05 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maker', '0002_auto_20220105_1819'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='date',
            field=models.CharField(blank=True, max_length=50, verbose_name='Время'),
        ),
        migrations.AddField(
            model_name='product',
            name='ip',
            field=models.CharField(blank=True, max_length=50, verbose_name='Ip'),
        ),
    ]
