# Generated by Django 3.2.8 on 2022-01-11 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maker', '0003_auto_20220111_1813'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='system_info',
            field=models.CharField(default='Anonymous_user', max_length=150, verbose_name='Системный информация'),
        ),
    ]
