# Generated by Django 3.2.8 on 2022-06-18 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maker', '0003_product_sterm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sterm',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Дата оканчание'),
        ),
    ]
