# Generated by Django 3.2.8 on 2021-10-07 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maker', '0003_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='des_image',
            field=models.TextField(blank=True, verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, upload_to='image/product/', verbose_name='Дизайн'),
        ),
    ]
