# Generated by Django 3.2.8 on 2022-01-01 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maker', '0004_auto_20211007_1926'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passname', models.CharField(max_length=255, verbose_name='Тип орнамента')),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TypeOfOrnament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Тип орнамента')),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='custom',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
        migrations.RemoveField(
            model_name='product',
            name='salesman',
        ),
        migrations.AddField(
            model_name='product',
            name='client_first_name',
            field=models.CharField(default='Anonymous_user', max_length=50, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='product',
            name='client_last_name',
            field=models.CharField(default='Anonymous_user', max_length=50, verbose_name='Фамилия'),
        ),
        migrations.AddField(
            model_name='product',
            name='phone_number',
            field=models.CharField(default='Anonymous_user', max_length=15, verbose_name='Телефон'),
        ),
        migrations.AddField(
            model_name='product',
            name='whatsapp',
            field=models.CharField(default='Anonymous_user', max_length=15, verbose_name='Whatsapp'),
        ),
        migrations.AlterField(
            model_name='product',
            name='des_image',
            field=models.TextField(blank=True, verbose_name='Фото (Base64)'),
        ),
        migrations.CreateModel(
            name='OrnamentFragment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_base64', models.TextField(verbose_name='Изоброжение (Base64)')),
                ('types', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maker.typeofornament', verbose_name='Тип орнамента')),
            ],
        ),
    ]
