# Generated by Django 3.2.8 on 2022-01-16 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maker', '0004_product_system_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ornament_info',
            field=models.CharField(default='Anonymous_user', max_length=90, verbose_name='Использованные узоры'),
        ),
    ]
