# Generated by Django 3.2.8 on 2021-12-29 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maker', '0004_auto_20211007_1926'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='custom',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
        migrations.RemoveField(
            model_name='product',
            name='salesman',
        ),
        migrations.AddField(
            model_name='product',
            name='client_first_name',
            field=models.CharField(default='Anonymous_user', max_length=50, verbose_name='Есімі'),
        ),
        migrations.AddField(
            model_name='product',
            name='client_last_name',
            field=models.CharField(default='Anonymous_user', max_length=50, verbose_name='Тегі'),
        ),
        migrations.AddField(
            model_name='product',
            name='phone_number',
            field=models.CharField(default='Anonymous_user', max_length=12, verbose_name='Телефон'),
        ),
        migrations.AddField(
            model_name='product',
            name='whatsapp',
            field=models.CharField(default='Anonymous_user', max_length=12, verbose_name='Whatsapp'),
        ),
    ]
