# Generated by Django 3.2.8 on 2021-12-29 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maker', '0005_auto_20211229_2211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='client_first_name',
            field=models.CharField(default='Anonymous_user', max_length=50, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='product',
            name='client_last_name',
            field=models.CharField(default='Anonymous_user', max_length=50, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='product',
            name='des_image',
            field=models.TextField(blank=True, verbose_name='Фото (Base64)'),
        ),
    ]
