# Generated by Django 3.2.8 on 2022-02-03 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maker', '0005_product_ornament_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='ornamentfragment',
            name='price',
            field=models.DecimalField(decimal_places=2, default=5000, max_digits=9, verbose_name='Цена орнамента'),
        ),
    ]
