# Generated by Django 3.2.8 on 2022-02-03 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maker', '0006_ornamentfragment_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='number',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=9, verbose_name='Количесвто'),
        ),
    ]
