# Generated by Django 3.2.8 on 2021-12-30 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maker', '0006_auto_20211229_2303'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeOfOrnaments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Тип орнамента')),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrnamentFragments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_base64', models.TextField(verbose_name='Изоброжение (Base64)')),
                ('types', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maker.typeofornaments', verbose_name='Тип орнамента')),
            ],
        ),
    ]
