# Generated by Django 3.2.8 on 2021-12-30 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maker', '0007_ornamentfragments_typeofornaments'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrnamentFragments',
            new_name='OrnamentFragment',
        ),
        migrations.RenameModel(
            old_name='TypeOfOrnaments',
            new_name='TypeOfOrnament',
        ),
    ]
