# Generated by Django 3.2.8 on 2022-02-03 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maker', '0007_product_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='number',
            field=models.DecimalField(decimal_places=0, default=1, max_digits=9, verbose_name='Количесвто'),
        ),
    ]
