# Generated by Django 3.2.8 on 2022-01-01 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maker', '0008_auto_20211230_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='phone_number',
            field=models.CharField(default='Anonymous_user', max_length=15, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='product',
            name='whatsapp',
            field=models.CharField(default='Anonymous_user', max_length=15, verbose_name='Whatsapp'),
        ),
    ]
