# Generated by Django 3.2.8 on 2022-06-05 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='premiumsubscribe',
            name='start_subscribe',
            field=models.DateTimeField(blank=True, verbose_name='Жазылым уақыты'),
        ),
    ]
