# Generated by Django 3.2.8 on 2022-05-28 07:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('members', '0003_alter_customer_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='PremiumSubscribe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_subscribe', models.DateTimeField(verbose_name='Жазылым уақыты')),
                ('end_subscribe', models.DateTimeField(verbose_name='Жазылым уақыты аяқталады')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
