# Generated by Django 3.2.8 on 2022-05-30 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_premiumsubscribe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='premiumsubscribe',
            name='end_subscribe',
            field=models.DateTimeField(blank=True, verbose_name='Жазылым уақыты аяқталады'),
        ),
        migrations.AlterField(
            model_name='premiumsubscribe',
            name='start_subscribe',
            field=models.DateTimeField(blank=True, verbose_name='Жазылым уақыты'),
        ),
    ]
