# Generated by Django 3.2.8 on 2022-06-01 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0007_alter_premiumsubscribe_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='premiumsubscribe',
            name='start_subscribe',
            field=models.CharField(blank=True, max_length=60, verbose_name='Жазылым уақыты'),
        ),
    ]
